# Generated by Django 5.2.5 on 2025-08-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education_experience_personalinfo_project_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('elegant', 'Elegant'), ('professional', 'Professional'), ('executive', 'Executive'), ('tech', 'Tech'), ('simple', 'Simple'), ('bold', 'Bold'), ('compact', 'Compact'), ('timeline', 'Timeline'), ('sidebar', 'Sidebar'), ('infographic', 'Infographic'), ('corporate', 'Corporate'), ('academic', 'Academic'), ('graduate', 'Graduate'), ('junior', 'Junior'), ('senior', 'Senior'), ('developer', 'Developer')], default='modern', max_length=20),
        ),
    ]
