# Generated by Django 5.2.5 on 2025-08-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_personalinfo_photo_url_alter_resume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='color_accent',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='resume',
            name='color_bg',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='resume',
            name='color_primary',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='resume',
            name='color_secondary',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='resume',
            name='color_text',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_family',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='resume',
            name='use_custom_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('elegant', 'Elegant'), ('professional', 'Professional'), ('executive', 'Executive'), ('tech', 'Tech'), ('simple', 'Simple'), ('bold', 'Bold'), ('compact', 'Compact'), ('timeline', 'Timeline'), ('sidebar', 'Sidebar'), ('infographic', 'Infographic'), ('corporate', 'Corporate'), ('academic', 'Academic'), ('graduate', 'Graduate'), ('junior', 'Junior'), ('senior', 'Senior'), ('developer', 'Developer'), ('custom', 'Custom Theme'), ('gradient', 'Gradient'), ('mono', 'Monochrome'), ('photo-left', 'Photo Left'), ('card', 'Card Sections'), ('material', 'Material'), ('neon', 'Neon'), ('pastel', 'Pastel'), ('newspaper', 'Newspaper'), ('grid', 'Grid')], default='modern', max_length=20),
        ),
    ]
