# Generated by Django 5.2.5 on 2025-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resume_color_accent_resume_color_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
